distributable:
  url: https://github.com/sunny0826/kubecm/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

display-name: kubecm

versions:
  github: sunny0826/kubecm/releases/tags

build:
  dependencies:
    go.dev: ^1.22
  script: |
    CGO_ENABLED=0 make build BUILD_TARGET_PKG_DIR={{ prefix }}/bin TAG={{ version }} KUBECM_VERSION={{ version }}

provides:
  - bin/kubecm

test:
  - kubecm version | grep {{ version }}
