distributable:
  url: https://github.com/sunny0826/kubecm/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

display-name: kubecm

versions:
  github: sunny0826/kubecm

build:
  dependencies:
    go.dev: ^1.22
  script: make build
  env:
    CGO_ENABLED: 0
    BUILD_TARGET_PKG_DIR: ${{ prefix }}/bin
    TAG: ${{ version }}
    KUBECM_VERSION: ${{ version }}

provides:
  - bin/kubecm

test:
  - kubecm version | grep {{ version }}
